// <auto-generated />
using System;
using RichDomainModel.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RichDomainModel.Migrations
{
    [DbContext(typeof(TriviaDbContext))]
    [Migration("20190403093934_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("RichDomainModel.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("RichDomainModel.Domain.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CurrentPlayerId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RichDomainModel.Domain.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameCategory");
                });

            modelBuilder.Entity("RichDomainModel.Domain.GameQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameCategoryId");

                    b.Property<bool>("NotUsed");

                    b.Property<int?>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("GameCategoryId");

                    b.HasIndex("QuestionId");

                    b.ToTable("GameQuestion");
                });

            modelBuilder.Entity("RichDomainModel.Domain.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameId");

                    b.Property<int>("GoldCoins");

                    b.Property<bool>("IsInPenaltyBox");

                    b.Property<int?>("LastQuestionId");

                    b.Property<string>("Name");

                    b.Property<int>("Place");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LastQuestionId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("RichDomainModel.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "sport 1",
                            CategoryId = 1,
                            Text = "Sport 1"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "sport 2",
                            CategoryId = 1,
                            Text = "Sport 2"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "sport 3",
                            CategoryId = 1,
                            Text = "Sport 3"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "sport 4",
                            CategoryId = 1,
                            Text = "Sport 4"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "sport 5",
                            CategoryId = 1,
                            Text = "Sport 5"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "sport 6",
                            CategoryId = 1,
                            Text = "Sport 6"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "sport 7",
                            CategoryId = 1,
                            Text = "Sport 7"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "sport 8",
                            CategoryId = 1,
                            Text = "Sport 8"
                        },
                        new
                        {
                            Id = 9,
                            Answer = "sport 9",
                            CategoryId = 1,
                            Text = "Sport 9"
                        },
                        new
                        {
                            Id = 10,
                            Answer = "sport 10",
                            CategoryId = 1,
                            Text = "Sport 10"
                        },
                        new
                        {
                            Id = 11,
                            Answer = "sport 11",
                            CategoryId = 1,
                            Text = "Sport 11"
                        },
                        new
                        {
                            Id = 12,
                            Answer = "sport 12",
                            CategoryId = 1,
                            Text = "Sport 12"
                        },
                        new
                        {
                            Id = 13,
                            Answer = "sport 13",
                            CategoryId = 1,
                            Text = "Sport 13"
                        },
                        new
                        {
                            Id = 14,
                            Answer = "sport 14",
                            CategoryId = 1,
                            Text = "Sport 14"
                        },
                        new
                        {
                            Id = 15,
                            Answer = "sport 15",
                            CategoryId = 1,
                            Text = "Sport 15"
                        },
                        new
                        {
                            Id = 16,
                            Answer = "sport 16",
                            CategoryId = 1,
                            Text = "Sport 16"
                        },
                        new
                        {
                            Id = 17,
                            Answer = "sport 17",
                            CategoryId = 1,
                            Text = "Sport 17"
                        },
                        new
                        {
                            Id = 18,
                            Answer = "sport 18",
                            CategoryId = 1,
                            Text = "Sport 18"
                        },
                        new
                        {
                            Id = 19,
                            Answer = "sport 19",
                            CategoryId = 1,
                            Text = "Sport 19"
                        },
                        new
                        {
                            Id = 20,
                            Answer = "sport 20",
                            CategoryId = 1,
                            Text = "Sport 20"
                        },
                        new
                        {
                            Id = 21,
                            Answer = "sport 21",
                            CategoryId = 1,
                            Text = "Sport 21"
                        },
                        new
                        {
                            Id = 22,
                            Answer = "sport 22",
                            CategoryId = 1,
                            Text = "Sport 22"
                        },
                        new
                        {
                            Id = 23,
                            Answer = "sport 23",
                            CategoryId = 1,
                            Text = "Sport 23"
                        },
                        new
                        {
                            Id = 24,
                            Answer = "sport 24",
                            CategoryId = 1,
                            Text = "Sport 24"
                        },
                        new
                        {
                            Id = 25,
                            Answer = "sport 25",
                            CategoryId = 1,
                            Text = "Sport 25"
                        },
                        new
                        {
                            Id = 26,
                            Answer = "sport 26",
                            CategoryId = 1,
                            Text = "Sport 26"
                        },
                        new
                        {
                            Id = 27,
                            Answer = "sport 27",
                            CategoryId = 1,
                            Text = "Sport 27"
                        },
                        new
                        {
                            Id = 28,
                            Answer = "sport 28",
                            CategoryId = 1,
                            Text = "Sport 28"
                        },
                        new
                        {
                            Id = 29,
                            Answer = "sport 29",
                            CategoryId = 1,
                            Text = "Sport 29"
                        },
                        new
                        {
                            Id = 30,
                            Answer = "sport 30",
                            CategoryId = 1,
                            Text = "Sport 30"
                        },
                        new
                        {
                            Id = 31,
                            Answer = "sport 31",
                            CategoryId = 1,
                            Text = "Sport 31"
                        },
                        new
                        {
                            Id = 32,
                            Answer = "sport 32",
                            CategoryId = 1,
                            Text = "Sport 32"
                        },
                        new
                        {
                            Id = 33,
                            Answer = "sport 33",
                            CategoryId = 1,
                            Text = "Sport 33"
                        },
                        new
                        {
                            Id = 34,
                            Answer = "sport 34",
                            CategoryId = 1,
                            Text = "Sport 34"
                        },
                        new
                        {
                            Id = 35,
                            Answer = "sport 35",
                            CategoryId = 1,
                            Text = "Sport 35"
                        },
                        new
                        {
                            Id = 36,
                            Answer = "sport 36",
                            CategoryId = 1,
                            Text = "Sport 36"
                        },
                        new
                        {
                            Id = 37,
                            Answer = "sport 37",
                            CategoryId = 1,
                            Text = "Sport 37"
                        },
                        new
                        {
                            Id = 38,
                            Answer = "sport 38",
                            CategoryId = 1,
                            Text = "Sport 38"
                        },
                        new
                        {
                            Id = 39,
                            Answer = "sport 39",
                            CategoryId = 1,
                            Text = "Sport 39"
                        },
                        new
                        {
                            Id = 40,
                            Answer = "sport 40",
                            CategoryId = 1,
                            Text = "Sport 40"
                        },
                        new
                        {
                            Id = 41,
                            Answer = "sport 41",
                            CategoryId = 1,
                            Text = "Sport 41"
                        },
                        new
                        {
                            Id = 42,
                            Answer = "sport 42",
                            CategoryId = 1,
                            Text = "Sport 42"
                        },
                        new
                        {
                            Id = 43,
                            Answer = "sport 43",
                            CategoryId = 1,
                            Text = "Sport 43"
                        },
                        new
                        {
                            Id = 44,
                            Answer = "sport 44",
                            CategoryId = 1,
                            Text = "Sport 44"
                        },
                        new
                        {
                            Id = 45,
                            Answer = "sport 45",
                            CategoryId = 1,
                            Text = "Sport 45"
                        },
                        new
                        {
                            Id = 46,
                            Answer = "sport 46",
                            CategoryId = 1,
                            Text = "Sport 46"
                        },
                        new
                        {
                            Id = 47,
                            Answer = "sport 47",
                            CategoryId = 1,
                            Text = "Sport 47"
                        },
                        new
                        {
                            Id = 48,
                            Answer = "sport 48",
                            CategoryId = 1,
                            Text = "Sport 48"
                        },
                        new
                        {
                            Id = 49,
                            Answer = "sport 49",
                            CategoryId = 1,
                            Text = "Sport 49"
                        },
                        new
                        {
                            Id = 50,
                            Answer = "sport 50",
                            CategoryId = 1,
                            Text = "Sport 50"
                        },
                        new
                        {
                            Id = 51,
                            Answer = "sport 51",
                            CategoryId = 1,
                            Text = "Sport 51"
                        },
                        new
                        {
                            Id = 52,
                            Answer = "sport 52",
                            CategoryId = 1,
                            Text = "Sport 52"
                        },
                        new
                        {
                            Id = 53,
                            Answer = "sport 53",
                            CategoryId = 1,
                            Text = "Sport 53"
                        },
                        new
                        {
                            Id = 54,
                            Answer = "sport 54",
                            CategoryId = 1,
                            Text = "Sport 54"
                        },
                        new
                        {
                            Id = 55,
                            Answer = "sport 55",
                            CategoryId = 1,
                            Text = "Sport 55"
                        },
                        new
                        {
                            Id = 56,
                            Answer = "sport 56",
                            CategoryId = 1,
                            Text = "Sport 56"
                        },
                        new
                        {
                            Id = 57,
                            Answer = "sport 57",
                            CategoryId = 1,
                            Text = "Sport 57"
                        },
                        new
                        {
                            Id = 58,
                            Answer = "sport 58",
                            CategoryId = 1,
                            Text = "Sport 58"
                        },
                        new
                        {
                            Id = 59,
                            Answer = "sport 59",
                            CategoryId = 1,
                            Text = "Sport 59"
                        },
                        new
                        {
                            Id = 60,
                            Answer = "sport 60",
                            CategoryId = 1,
                            Text = "Sport 60"
                        },
                        new
                        {
                            Id = 61,
                            Answer = "sport 61",
                            CategoryId = 1,
                            Text = "Sport 61"
                        },
                        new
                        {
                            Id = 62,
                            Answer = "sport 62",
                            CategoryId = 1,
                            Text = "Sport 62"
                        },
                        new
                        {
                            Id = 63,
                            Answer = "sport 63",
                            CategoryId = 1,
                            Text = "Sport 63"
                        },
                        new
                        {
                            Id = 64,
                            Answer = "sport 64",
                            CategoryId = 1,
                            Text = "Sport 64"
                        },
                        new
                        {
                            Id = 65,
                            Answer = "sport 65",
                            CategoryId = 1,
                            Text = "Sport 65"
                        },
                        new
                        {
                            Id = 66,
                            Answer = "sport 66",
                            CategoryId = 1,
                            Text = "Sport 66"
                        },
                        new
                        {
                            Id = 67,
                            Answer = "sport 67",
                            CategoryId = 1,
                            Text = "Sport 67"
                        },
                        new
                        {
                            Id = 68,
                            Answer = "sport 68",
                            CategoryId = 1,
                            Text = "Sport 68"
                        },
                        new
                        {
                            Id = 69,
                            Answer = "sport 69",
                            CategoryId = 1,
                            Text = "Sport 69"
                        },
                        new
                        {
                            Id = 70,
                            Answer = "sport 70",
                            CategoryId = 1,
                            Text = "Sport 70"
                        },
                        new
                        {
                            Id = 71,
                            Answer = "sport 71",
                            CategoryId = 1,
                            Text = "Sport 71"
                        },
                        new
                        {
                            Id = 72,
                            Answer = "sport 72",
                            CategoryId = 1,
                            Text = "Sport 72"
                        },
                        new
                        {
                            Id = 73,
                            Answer = "sport 73",
                            CategoryId = 1,
                            Text = "Sport 73"
                        },
                        new
                        {
                            Id = 74,
                            Answer = "sport 74",
                            CategoryId = 1,
                            Text = "Sport 74"
                        },
                        new
                        {
                            Id = 75,
                            Answer = "sport 75",
                            CategoryId = 1,
                            Text = "Sport 75"
                        },
                        new
                        {
                            Id = 76,
                            Answer = "sport 76",
                            CategoryId = 1,
                            Text = "Sport 76"
                        },
                        new
                        {
                            Id = 77,
                            Answer = "sport 77",
                            CategoryId = 1,
                            Text = "Sport 77"
                        },
                        new
                        {
                            Id = 78,
                            Answer = "sport 78",
                            CategoryId = 1,
                            Text = "Sport 78"
                        },
                        new
                        {
                            Id = 79,
                            Answer = "sport 79",
                            CategoryId = 1,
                            Text = "Sport 79"
                        },
                        new
                        {
                            Id = 80,
                            Answer = "sport 80",
                            CategoryId = 1,
                            Text = "Sport 80"
                        },
                        new
                        {
                            Id = 81,
                            Answer = "sport 81",
                            CategoryId = 1,
                            Text = "Sport 81"
                        },
                        new
                        {
                            Id = 82,
                            Answer = "sport 82",
                            CategoryId = 1,
                            Text = "Sport 82"
                        },
                        new
                        {
                            Id = 83,
                            Answer = "sport 83",
                            CategoryId = 1,
                            Text = "Sport 83"
                        },
                        new
                        {
                            Id = 84,
                            Answer = "sport 84",
                            CategoryId = 1,
                            Text = "Sport 84"
                        },
                        new
                        {
                            Id = 85,
                            Answer = "sport 85",
                            CategoryId = 1,
                            Text = "Sport 85"
                        },
                        new
                        {
                            Id = 86,
                            Answer = "sport 86",
                            CategoryId = 1,
                            Text = "Sport 86"
                        },
                        new
                        {
                            Id = 87,
                            Answer = "sport 87",
                            CategoryId = 1,
                            Text = "Sport 87"
                        },
                        new
                        {
                            Id = 88,
                            Answer = "sport 88",
                            CategoryId = 1,
                            Text = "Sport 88"
                        },
                        new
                        {
                            Id = 89,
                            Answer = "sport 89",
                            CategoryId = 1,
                            Text = "Sport 89"
                        },
                        new
                        {
                            Id = 90,
                            Answer = "sport 90",
                            CategoryId = 1,
                            Text = "Sport 90"
                        },
                        new
                        {
                            Id = 91,
                            Answer = "sport 91",
                            CategoryId = 1,
                            Text = "Sport 91"
                        },
                        new
                        {
                            Id = 92,
                            Answer = "sport 92",
                            CategoryId = 1,
                            Text = "Sport 92"
                        },
                        new
                        {
                            Id = 93,
                            Answer = "sport 93",
                            CategoryId = 1,
                            Text = "Sport 93"
                        },
                        new
                        {
                            Id = 94,
                            Answer = "sport 94",
                            CategoryId = 1,
                            Text = "Sport 94"
                        },
                        new
                        {
                            Id = 95,
                            Answer = "sport 95",
                            CategoryId = 1,
                            Text = "Sport 95"
                        },
                        new
                        {
                            Id = 96,
                            Answer = "sport 96",
                            CategoryId = 1,
                            Text = "Sport 96"
                        },
                        new
                        {
                            Id = 97,
                            Answer = "sport 97",
                            CategoryId = 1,
                            Text = "Sport 97"
                        },
                        new
                        {
                            Id = 98,
                            Answer = "sport 98",
                            CategoryId = 1,
                            Text = "Sport 98"
                        },
                        new
                        {
                            Id = 99,
                            Answer = "sport 99",
                            CategoryId = 1,
                            Text = "Sport 99"
                        },
                        new
                        {
                            Id = 100,
                            Answer = "sport 100",
                            CategoryId = 1,
                            Text = "Sport 100"
                        });
                });

            modelBuilder.Entity("RichDomainModel.Domain.Game", b =>
                {
                    b.HasOne("RichDomainModel.Domain.Player", "CurrentPlayer")
                        .WithMany()
                        .HasForeignKey("CurrentPlayerId");
                });

            modelBuilder.Entity("RichDomainModel.Domain.GameCategory", b =>
                {
                    b.HasOne("RichDomainModel.Domain.Game")
                        .WithMany("Categories")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("RichDomainModel.Domain.GameQuestion", b =>
                {
                    b.HasOne("RichDomainModel.Domain.GameCategory")
                        .WithMany("Questions")
                        .HasForeignKey("GameCategoryId");

                    b.HasOne("RichDomainModel.Domain.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("RichDomainModel.Domain.Player", b =>
                {
                    b.HasOne("RichDomainModel.Domain.Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId");

                    b.HasOne("RichDomainModel.Domain.Question", "LastQuestion")
                        .WithMany()
                        .HasForeignKey("LastQuestionId");
                });

            modelBuilder.Entity("RichDomainModel.Domain.Question", b =>
                {
                    b.HasOne("RichDomainModel.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
